### ISSUE TITLE
TremorSense makes Mining Faster [PK 1.8.9 Beta]

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1010]
How to recreate bug:
With the tremorsense glow passive enabled, mine the glowstone under your feet and it will allow you to mine the block faster (works with bare fists too I think, just takes longer time for the block to disappear for some reason)

**Comment by Simplicitee** [comment]
I think what's happening is when you break the glowstone, your client tells the server "hey i'm breaking this block", but the glowstone is only for the client so the server thinks you're trying to break the actual block. That's why it takes longer for the block to disappear, the server still thinks you're breaking the actual block and since it takes longer to mine most blocks barehanded, it takes longer for the actual block to disappear. I don't really know if there's anything we can do about this.

**Comment by ChaoZed** [comment]
Maybe disabling the glowstone when it is hit so that the player can mine the block normally?

**Comment by Varhagna** [comment]
We most likely will not fix this for the 1.9.0 release, and with the focus shifting to the overhaul I'm leaving this to any developer who wants to fix it.

**Comment by StrangeOne101** [comment]
If this is still an issue, it can be resolved by canceling the block break event if the block is equal to the current tremorsense block. Doing so should also hide the glowstone so it can be broken properly next time
