### ISSUE TITLE
[PK 1.8.9] Dropping items makes you commit ability

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1048]
As title says.
https://gyazo.com/55bc7e949dd055c32f277a93a31ea3e2

Credits to BlackXLight for first finding this issue. I'm just making this on here so that it doesn't go forgotten.

**Comment by xNuminousx** [comment]
This is caused by the PlayerInteractEvent. That event doesn't have a check (that I can see) that will tell the code whether or not it's being executed because of an item drop or not. May need to use a different event to check for left clicks or create a custom event that extends PlayerInteractEvent,

**Comment by xNuminousx** [comment]
I was able to solve this a different way :) Ignore what I said before lol

**Comment by Rabidhuman** [comment]
Having this issue as well, still.
on 
PK 1.8.9 
Paper 1.15.2

**Comment by xNuminousx** [comment]
this has already been fixed as of #1051 it just needs to be approved

**Comment by ChristopherWMM** [comment]
Fixed as of #1051
