### ISSUE TITLE
Players cannot bend inside their own Kingdom

### ISSUE THREAD

**Issue by Leomelonseeds** [ProjectKorra/ProjectKorra#1158]
Hello there,

As seen in the title, KingdomsX integration makes players unable to bend inside Kingdom territory, including their own. There should perhaps be an option to allow this, since players will question if this is intended behaviour.

Additionally, whenever a bending move is attempted in Kingdom territory, console is spammed with similar errors to:
![image](https://user-images.githubusercontent.com/17891302/124032882-0963bb80-d9ae-11eb-86ef-8efb2711ec70.png)

If you could take a look at this, it would be much appreciated. Thanks!

**Comment by ChristopherWMM** [comment]
Hello, thank you for the bug report. Can you provide us with a little bit of information? If you run the `/pk debug` command a `debug.txt` file should be created in the plugins root directory (`plugins/ProjectKorra/`). Can you share the contents of that file? Otherwise, I will need your KingdomsX version and server MC version.

**Comment by StrangeOne101** [comment]
Kingdoms support has been upgraded in #1221. It works perfectly fine in that, so closing for now
