### ISSUE TITLE
Staff List URL Broken

### ISSUE THREAD

**Issue by echo35** [ProjectKorra/ProjectKorra#625]
Periodical errors show in the server log as this Runnable executes: [WhoCommand.java:57](https://github.com/ProjectKorra/ProjectKorra/blob/master/src/com/projectkorra/projectkorra/command/WhoCommand.java#L57), because the provided URL [http://www.projectkorra.com/internals/staff.html](http://www.projectkorra.com/internals/staff.html) returns a 404 page, rather than the expected text file.

I'm do not know what the correct URL is, therefore am unable to submit a PR. Because it is causing me (and probably other servers) periodic console errors, I think it should be looked into.

**Comment by MistPhizzle** [comment]
Hi! Thanks for the issue report.

It is worth noting that because it is on git, doesn't necessarily mean it is released. We do not provide support for unreleased builds.

The issue with the staff page is because it actually should point to http://projectkorra.com/staff.html

This is fixed, just not pushed to Git yet. But in the future we do not provide support for features not yet released.

**Comment by echo35** [comment]
Good to know. 
I'm aware that these features are unsupported, I just felt the need to point it out in case it went unnoticed.

Thanks for the quick reply Mist!
--Carbogen
