### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by Loonyy** [ProjectKorra/ProjectKorra#929]
Server froze, got this error:
https://pastebin.com/sV3hpRQc

**Comment by xNuminousx** [comment]
Are you in WIP build? If not, this could have been fixed or if so, Sobki's changes may have fixed this. I just notice "pk_cooldowns" being involved in his changes here: 4d57572

**Comment by jayoevans** [comment]
It is likely this error has occurred because you were running a previous build off of the WIP branch which would have generated the pk_cooldowns table. When updating to the most recent build off of WIP, the structure of the pk_cooldowns table would have changed. To fix this you'll need to delete the pk_cooldowns table from your database to allow ProjectKorra to recreate the table.

**Comment by jayoevans** [comment]
I don't think it will be an issue as servers shouldn't really be running wip versions on their production servers. Having said that, the more technically able who are more likely to be the ones run wip builds shouldn't have an issue deleting a table.

**Comment by Loonyy** [comment]
Well if releases didn't take 5 years people wouldn't have to use WIP tbf
