### ISSUE TITLE
NoSuchElement Exception.

### ISSUE THREAD

**Issue by ronfarkash** [ProjectKorra/ProjectKorra#956]
1. Downloaded ProjectKorra as a .zip through clone/download.
2. Opened it up in Eclipse.
3. Editted a certain Earth ability.
4. Exported as jar.
5. Opened test server and I get the NoSuchElement exception.
6. Reverted Earth ability changes I have done to the original version.
7. Went to the area the error was at and debugged the paths.
`Enumeration<URL> resources = this.loader.getResources(path);`
`			String jarloc = resources.nextElement().getPath();`
`                        System.out.println(jarloc);`
`			jarloc = jarloc.substring(5, jarloc.length() - path.length() - 2);`
`			System.out.println(jarloc);`
`			String s = URLDecoder.decode(jarloc, "UTF-8");`
`			System.out.println(s);`
`	                jar = new JarFile(new File(s));`
8. Re-exported and ran the server, got the same error.
Error seems to be at this line:
`String jarloc = resources.nextElement().getPath();`

No clue why it happens.

**Comment by StrangeOne101** [comment]
This error happens because you didn't compile ProjectKorra with Maven. Since 1.12 modified how the guava library worked, we had to change the ability loader to use the metadata provided in .jar files. But for some reason, the metadata only works when the plugin is compiled with Maven.

Running `maven install` should fix your issues.

**Comment by ronfarkash** [comment]
Could you explain me how do I run maven install, I have never used maven before.

**Comment by StrangeOne101** [comment]
![image](https://user-images.githubusercontent.com/2769013/41467048-07338488-70f9-11e8-94d2-44da66a5e700.png)

After that, if the log says `BUILD SUCCESSFUL`, it will appear in the `target` directory with the name `ProjectKorra-1.8.X.jar` (ignore the other files)

**Comment by ronfarkash** [comment]
And that is how I export the project from now and on if I change anything in it?

**Comment by StrangeOne101** [comment]
Yes, you just do that. It's the same as exporting the jar normally but the destination is pre-determined.

**Comment by ronfarkash** [comment]
Just so I understand, is it the job of build.xml to put that same metadata in the jar and that helps the AbilityLoader to find where the abilities are?

Wow 1.12 really messed up things.

**Comment by StrangeOne101** [comment]
I was really describing what happens briefly from memory but you made me dive back into how we did it again haha.

In the new ability loader, we get all resources provided in the jar and go through all of them to find classes that match the criteria of a stock plugin ability. Normally, resources are just things like extra files, such as the plugin.yml, etc. However it seems that Maven also registers all classes in the jar metadata as resources, which is what allows us to cycle through them to see which classes are abilities.

Pre-1.12, guava could tell us what classes existed within the current jar and not just within the Java Runtime Environment instance. But since that no longer works, we use Maven's ability to map the class structure as resources to our advantage.

Hope that answers your question. And yes, although it did mess things up a little bit, it only affects the classloading of abilities in ProjectKorra (which, most of the time, only affects the jar we distribute).

**Comment by ronfarkash** [comment]
Alright thank you very much.
